### ISSUE TITLE
eval using the juy-theses eng-test returns file not found for everything.

### ISSUE THREAD

**Issue by Hurttaj** [NatLibFi/Annif-corpora#8]
It looks like the links contained in eng-test are looking for .txts and everything in juy-theses eng is .url. This seems to be true of all of the example document corpuses. I haven't tested all of them, but it looks like all of them would break.

**Comment by osma** [comment]
We cannot include the .txt files in this repository due to copyright reasons. They must be downloaded separately. There is a Makefile to automate all this. See [here](https://github.com/NatLibFi/Annif-corpora/blob/master/fulltext/jyu-theses/README.md)

Some of the JYU documents (English language only) are also included in the Annif tutorial materials and the same applies there. There is [a video](https://www.youtube.com/watch?v=S4E3d3o5HWg&list=PLa9kvrI3VLf5K-bjvVDaIWMi5CACGjPUM&index=5) that explains the process and shows how to download the PDFs and convert them to text.

**Comment by Hurttaj** [comment]
Ah, thanks for your prompt response and sorry for the non-bug bug report.
